// app/(tabs)/exercises/styles/index.ts
import { Dimensions, Platform, StyleSheet } from "react-native";

const SCREEN_WIDTH = Dimensions.get("window").width;

export const styles = StyleSheet.create({
  // ==================== 主页面 ====================
  container: { flex: 1, backgroundColor: "#fafafa" },
  topBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "#6a4c93",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
      android: { elevation: 4 },
    }),
  },
  title: { fontSize: 20, fontWeight: "600", color: "#fff" },

  // ==================== 支持提示 Banner ====================
  supportBanner: {
    backgroundColor: "#f3eef8",
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 4,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e0d4f0",
  },
  bannerRow: { flexDirection: "row", alignItems: "center" },
  bannerTitle: {
    fontSize: 14,
    color: "#444",
    marginLeft: 8,
    fontWeight: "500",
  },
  supportHighlight: { fontWeight: "700", color: "#6a4c93" },
  bannerDivider: { height: 1, backgroundColor: "#e0d4f0", marginVertical: 8 },
  bannerTipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-around",
    rowGap: 8,
  },
  tipItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    width: "50%",
    justifyContent: "center",
  },
  tipText: { fontSize: 12, color: "#666", fontWeight: "500" },

  // ==================== 记录列表 ====================
  listContainer: { paddingBottom: 100 },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 100,
  },
  emptyText: { fontSize: 18, color: "#666", marginBottom: 8, marginTop: 16 },
  emptySubtext: { fontSize: 14, color: "#999" },
  emptySupportTag: {
    marginTop: 24,
    backgroundColor: "#f3eef8",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  emptySupportText: { fontSize: 13, color: "#6a4c93", fontWeight: "500" },

  // ==================== 记录卡片 ====================
  itemCard: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 8,
    marginHorizontal: 16,
    marginBottom: 12,
    overflow: "hidden",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
      },
      android: { elevation: 2 },
    }),
  },
  thumbnailWrapper: { width: 120, height: 80, justifyContent: "flex-end" },
  thumbnail: { width: "100%", height: "100%", resizeMode: "cover" },
  loadingPlaceholder: {
    width: "100%",
    height: "100%",
    backgroundColor: "#f5f5f5",
    justifyContent: "flex-end",
    alignItems: "center",
    paddingBottom: 4,
  },
  durationText: {
    fontSize: 12,
    color: "#fff",
    backgroundColor: "rgba(0,0,0,0.6)",
    paddingHorizontal: 4,
    borderRadius: 2,
  },
  emptyThumbnail: {
    width: "100%",
    height: "100%",
    backgroundColor: "#f0f0f0",
    justifyContent: "center",
    alignItems: "center",
  },
  noThumbnailText: { fontSize: 12, color: "#999", marginTop: 4 },

  infoSection: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    justifyContent: "space-between",
  },
  cardRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 28,
  },
  dateRow: { flexDirection: "row", alignItems: "center" },
  dateText: { marginLeft: 6, fontSize: 15, fontWeight: "600", color: "#333" },
  metaRow: { flexDirection: "row", alignItems: "center" },
  metaText: { marginLeft: 6, fontSize: 13, color: "#666" },

  // ==================== 浮动按钮 ====================
  fabButton: {
    position: "absolute",
    right: 20,
    bottom: 24,
    backgroundColor: "#6a4c93",
    borderRadius: 28,
    paddingHorizontal: 20,
    paddingVertical: 14,
    ...Platform.select({
      ios: {
        shadowColor: "#6a4c93",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: { elevation: 8 },
    }),
  },
  fabButtonDisabled: { backgroundColor: "#7a5a8f" },
  fabContent: { flexDirection: "row", alignItems: "center", gap: 8 },
  fabText: { color: "#fff", fontSize: 15, fontWeight: "600" },

  // ==================== 上传锁定弹窗 ====================
  lockModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.75)",
    justifyContent: "center",
    alignItems: "center",
  },
  lockModalContainer: {
    backgroundColor: "#fff",
    borderRadius: 20,
    paddingVertical: 36,
    paddingHorizontal: 32,
    alignItems: "center",
    width: "82%",
    maxWidth: 340,
  },
  lockProgressNumber: {
    fontSize: 48,
    fontWeight: "800",
    color: "#6a4c93",
    marginBottom: 4,
    fontVariant: ["tabular-nums"],
  },
  lockAnalyzingIcon: { fontSize: 42, marginBottom: 8 },
  lockModalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#333",
    marginBottom: 16,
  },
  lockProgressBarBg: {
    width: "100%",
    height: 12,
    backgroundColor: "#e8e8e8",
    borderRadius: 6,
    overflow: "hidden",
    marginBottom: 10,
  },
  lockProgressBarFill: {
    height: "100%",
    borderRadius: 6,
    backgroundColor: "#6a4c93",
  },
  lockProgressBarIndeterminate: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: "40%",
    backgroundColor: "#6a4c93",
    borderRadius: 6,
  },
  lockModalStatus: {
    fontSize: 14,
    fontWeight: "600",
    color: "#555",
    marginBottom: 8,
  },
  lockModalDesc: {
    fontSize: 13,
    color: "#888",
    textAlign: "center",
    lineHeight: 20,
  },

  // ==================== 分析弹窗 ====================
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "92%",
    minHeight: "60%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  modalTitle: { fontSize: 20, fontWeight: "600", color: "#333" },
  modalSubtitle: { fontSize: 13, color: "#888", marginTop: 2 },
  modalContent: { paddingHorizontal: 20, paddingVertical: 16 },
  analysisSection: {
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#6a4c93",
    marginBottom: 12,
  },
  infoRow: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
  infoLabel: { fontSize: 14, color: "#666", marginLeft: 8, marginRight: 8 },
  infoValue: { fontSize: 14, color: "#333", flex: 1 },
  scoreText: { fontSize: 18, fontWeight: "bold", color: "#FFD700" },
  featureItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  featureContent: { marginLeft: 12, flex: 1 },
  featureTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
    marginBottom: 4,
  },
  featureDesc: { fontSize: 13, color: "#666", lineHeight: 20 },
  feedbackText: { fontSize: 14, color: "#4CAF50", lineHeight: 22 },
  closeButton: {
    backgroundColor: "#6a4c93",
    marginHorizontal: 20,
    marginBottom: 20,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: "center",
  },
  closeButtonText: { color: "#fff", fontSize: 16, fontWeight: "600" },
  feedbackItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  feedbackBullet: { width: 20, alignItems: "center", paddingTop: 6 },
  bulletDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#4CAF50",
  },

  // ==================== V7.0 总览 ====================
  overviewRow: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  scoreRing: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 3,
    borderColor: "#e0e0e0",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  scoreRingText: { fontSize: 24, fontWeight: "800" },
  scoreRingLabel: { fontSize: 10, color: "#999", marginTop: -2 },
  overviewStats: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
  },
  overviewStatItem: { alignItems: "center" },
  overviewStatValue: { fontSize: 16, fontWeight: "700", color: "#333" },
  overviewStatLabel: { fontSize: 11, color: "#999", marginTop: 2 },
  patternTag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f3eef8",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    alignSelf: "flex-start",
    gap: 6,
  },
  patternTagText: { fontSize: 12, color: "#6a4c93", fontWeight: "500" },

  // ==================== 错误卡片 ====================
  errorCard: {
    backgroundColor: "#fafafa",
    borderRadius: 10,
    padding: 14,
    marginBottom: 12,
    borderLeftWidth: 4,
  },
  errorCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 8,
  },
  errorSeverityBadge: { fontSize: 12 },
  errorName: { fontSize: 15, fontWeight: "600", color: "#333", flex: 1 },
  errorMetricRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    gap: 12,
  },
  errorMetricItem: { alignItems: "center" },
  errorMetricLabel: { fontSize: 11, color: "#999" },
  errorMetricValue: { fontSize: 18, fontWeight: "700", color: "#333" },
  errorDetailRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 6,
    gap: 6,
  },
  errorRiskText: { fontSize: 12, color: "#FF5722", flex: 1, lineHeight: 18 },
  errorFeedbackText: { fontSize: 12, color: "#333", flex: 1, lineHeight: 18 },
  errorDrillsRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    backgroundColor: "#f3eef8",
    borderRadius: 6,
    padding: 8,
    marginTop: 4,
  },
  errorDrillsText: { fontSize: 12, color: "#6a4c93", flex: 1 },
  errorPhaseTags: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    marginTop: 6,
  },
  phaseTag: {
    backgroundColor: "#e8e8e8",
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  phaseTagText: { fontSize: 10, color: "#666" },

  // ==================== Rep 选择器与详情 ====================
  repSelectorRow: { marginBottom: 12 },
  repSelectorChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: "#f0f0f0",
    marginRight: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  repSelectorChipActive: { backgroundColor: "#6a4c93" },
  repSelectorText: { fontSize: 13, fontWeight: "600", color: "#666" },
  repSelectorTextActive: { color: "#fff" },
  repErrorDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#F44336",
  },
  repDetailCard: { backgroundColor: "#f8f9fa", borderRadius: 10, padding: 14 },
  repDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  repDetailLabel: { fontSize: 13, color: "#888" },
  repDetailValue: { fontSize: 13, fontWeight: "600", color: "#333" },
  phaseTimeline: { marginTop: 8 },
  phaseTimelineBar: {
    flexDirection: "row",
    height: 24,
    borderRadius: 6,
    overflow: "hidden",
    marginTop: 6,
    backgroundColor: "#e8e8e8",
  },
  phaseBlock: {
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 4,
  },
  phaseBlockText: { fontSize: 9, color: "#fff", fontWeight: "600" },
  repErrorsSection: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#e8e8e8",
    paddingTop: 8,
  },
  repErrorItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  repErrorIcon: { fontSize: 12 },
  repErrorName: { fontSize: 12, color: "#333" },

  // ==================== 角度曲线 ====================
  curveSubtitle: {
    fontSize: 11,
    color: "#999",
    marginBottom: 8,
    marginTop: -6,
  },
  curveCard: {
    marginBottom: 16,
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
    padding: 12,
  },
  curveHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  curveName: { fontSize: 13, fontWeight: "600", color: "#333" },
  curveRange: { fontSize: 12, color: "#6a4c93", fontWeight: "500" },
  curveChart: {
    position: "relative",
    backgroundColor: "#fff",
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#eee",
  },
  curveGridLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "#f0f0f0",
  },
  curvePoint: { position: "absolute", width: 3, height: 3, borderRadius: 1.5 },
  curveAxisLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 4,
  },
  curveAxisLabel: { fontSize: 10, color: "#bbb" },

  // ==================== 骨骼关键帧 ====================
  skeletonFramesRow: { flexDirection: "row", gap: 12 },
  skeletonFrameCard: {
    width: 190,
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
    padding: 8,
    alignItems: "center",
  },
  skeletonFramePct: {
    fontSize: 12,
    fontWeight: "700",
    color: "#6a4c93",
    marginBottom: 4,
  },
  skeletonCanvas: {
    width: 160,
    height: 160,
    backgroundColor: "#1a1a2e",
    borderRadius: 6,
    position: "relative",
    overflow: "hidden",
  },
  skeletonBone: {
    position: "absolute",
    height: 3,
    backgroundColor: "#29B6F6",
    borderRadius: 1.5,
  },
  skeletonJoint: {
    position: "absolute",
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#FFD54F",
  },
  skeletonAngleText: {
    fontSize: 9,
    color: "#666",
    marginTop: 2,
    textAlign: "center",
  },
  skeletonLegend: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 4,
    marginTop: 6,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: "#e0e0e0",
  },
  skeletonLegendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  skeletonLegendDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
  },
  skeletonLegendText: {
    fontSize: 8,
    color: "#888",
  },

  // ==================== 轨迹分析 ====================
  trajSummaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#eee",
  },
  trajSummaryLabel: { fontSize: 13, color: "#666" },
  trajSummaryValue: { fontSize: 13, fontWeight: "600", color: "#333" },
  trajProgressRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  trajProgressBarBg: {
    flex: 1,
    height: 8,
    backgroundColor: "#e8e8e8",
    borderRadius: 4,
    marginRight: 8,
    overflow: "hidden",
  },
  trajProgressBarFill: {
    height: "100%",
    backgroundColor: "#6a4c93",
    borderRadius: 4,
  },
  trajProgressText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#6a4c93",
    width: 36,
    textAlign: "right",
  },
  trajectoryContainer: {
    marginTop: 8,
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
    padding: 12,
  },
  trajectoryLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#6a4c93",
    marginBottom: 8,
  },
  trajectoryPoint: { marginBottom: 8 },
  trajectoryText: { fontSize: 12, color: "#555", fontFamily: "monospace" },
  trajectoryMore: {
    fontSize: 12,
    color: "#999",
    fontStyle: "italic",
    marginTop: 4,
  },

  // ==================== 疲劳分析卡片 ====================
  fatigueCard: {
    backgroundColor: "#f8f9fa",
    borderRadius: 10,
    padding: 14,
  },
  fatigueRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#eee",
  },
  fatigueLabel: { fontSize: 13, color: "#888" },
  fatigueValue: { fontSize: 15, fontWeight: "700", color: "#333" },
  fatigueValueSmall: {
    fontSize: 11,
    fontWeight: "600",
    color: "#666",
    maxWidth: "60%",
    textAlign: "right",
  },
});
